### ISSUE TITLE
Hides all files

### ISSUE THREAD

**Issue by bitbit-gmbh** [DimitrK/exclude-indexing-filetree#1]
Hi,

I installed your extension, and added the .brackets.json file to the root of my current project, with the following content:

{
    "dimitrk.exclude-indexing-filetree.excludeList": [
        "node_modules"
    ]
}

I'm using in addtion the "Projects" extension.
When I restart brackets, all files will dissappear in the project folder within this extension.

Cheers,
Alex

**Comment by DimitrK** [comment]
Hello Alex, 
Thanks for your feedback.
You shouldn't have to add this exclude list definition since by default the extension hides all files located in the following folders:

```
      '.git(?!ignore)',
      'dist',
      'bower_components',
      'node_modules'
```

Nevertheless, this appears to be a bug so I ll leave the ticket open until I will take a closer look at it.

**Comment by gld1982ltd** [comment]
This does the same thing to me. All files are hidden.

**Comment by cmoeser** [comment]
Same here, all files are hidden.

**Comment by DimitrK** [comment]
I am unable to replicate that on my setup. Could you please provide more info ?

**Comment by cmoeser** [comment]
I'm on WIndows 8 
Brackets Release 1.7 build 1.7.0-16898 (release b0a363b71) 

Have tried disabling all other extensions as well as trying a few different project folders. It shows some directories empty with no files. Some directories are missing though. 

It's worth noting when I open Brackets all files and directories do show, then there's a flash, then just empty folders.

Best,
-Chip

![screenshot](https://cloud.githubusercontent.com/assets/2686223/15986717/2bc9444a-2fdd-11e6-828d-21c046e0b01a.jpg)

**Comment by rickbenetti** [comment]
Hi @DimitrK ,
I get same problem @cmoeser have.

My config is:

```
Mac Os X Yosemite 10.10.5
Release 1.7 build 1.7.0-16898 (release b0a363b71) 
build timestamp: Wed Jun 08 2016 04:20:22 GMT-0700
```

Is I configure **.brackets.json** at root my project all folders gone, and I work with Magento 1.9.2.4, if you don't know the Magento projects has more than **35.000** files and **360MB** including .git folder off course.

**Comment by musicbender** [comment]
Exact same issue as @cmoeser  describes. With and without populating the exclusion list. 

`macOS Sierra 10.12`
`Release 1.7 build 1.7.0-16898 (release b0a363b71)`
`build timestamp: Wed Jun 08 2016 04:20:22 GMT-0700`

**Comment by ChrisHouston** [comment]
I have just experienced this error, and have found that this line in .gitignore seemed to be the culprit:

._*

Commenting that line fixes the issue, putting it back in hides everything except the files in the root of the project.

**Comment by ChrisHouston** [comment]
Manually applying the code in this pull request fixes the issue:

https://github.com/DimitrK/exclude-indexing-filetree/pull/4

**Comment by DimitrK** [comment]
#4
